### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [sciurius/perl-HarfBuzz-Shaper#8]
This is a continuation of https://github.com/ChordPro/chordpro/issues/117#issuecomment-691663531

Build Log:
[zhws6c5r9id13235qr79417i4qvhhc-perl-harfbuzz-shaper-0.023.drv.log](https://github.com/sciurius/perl-HarfBuzz-Shaper/files/5216093/zhws6c5r9id13235qr79417i4qvhhc-perl-harfbuzz-shaper-0.023.drv.log)

**Comment by sciurius** [comment]
Thanks for reporting.
You seem to have a very uncommon system setup. CPAN kits are intended to be build using the `cpan` or `cpanm` tool so this may induce surprises.

The error you get is due to a load failure of the harfbuzz library. It is missing entry point `hb_font_set_ptem`. This entry point was added to the harfbuzz library in version 1.6.0 (2017!) but it may be possible that your system still has an even older version.
On the other hand, the build procedure did already verify that there is a usuable harfbuzz library (line 352: "using platform library") -- and succeeds, while a couple of lines later it reports "No library found for -lharfbuzz". The build procedure checks for libraries in common places like `/lib`, '/use/local/lib` etc and it seems to detect a usuable library there. But the actual compile and link phase use a quite different environment in `/gnu/store/8zvc5mvk0xm3ygrxsgpyy5ilxb5rzjry-perl-5.30.2/`.

The only suggestion I can give is to contact your platform support.

You may try to change line 64 of Makefile.PL into `my $hb_include = 1` and see if this helps.

**Comment by peanutbutterandcrackers** [comment]
The issue was resolved by explicitly pointing the path to the harbuzz library by manually passing `LIBS=-L/path/to/harfbuzz/lib -lharfbuzz` during the call the `perl Makefile.PL`.

Here is the log: 
[b0rn7cn0kf1ssip45rpyb1rhhn9d8j-perl-harfbuzz-shaper-0.023.drv.log](https://github.com/sciurius/perl-HarfBuzz-Shaper/files/5219306/b0rn7cn0kf1ssip45rpyb1rhhn9d8j-perl-harfbuzz-shaper-0.023.drv.log)

Please do let me know if something is amiss there. (Because it seems `chordpro-next` is still not rendering Devanagari correctly for me. It's probably a packaging issue. But I want to completely rule this module out, as a culprit.)

**Comment by peanutbutterandcrackers** [comment]
Update, `chordpro-next` runs fine with a `--config` file specified, as you said. So, this thing works. Thank you very much.

Closing this as resolved.

**Comment by sciurius** [comment]
Thanks for your persistence and confidence!
